name: Deploy lambda function

on:
   push:
      branches:
        - main

jobs:
  Checkout-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
  Deploy:
    needs: Checkout-code
    runs-on: ubuntu-latest

    steps:
      - name: Install Zip Tool
        uses: montudor/action-zip@v1
      - name: Create Zip File for Lambda Function
        run: zip -r code.zip . -i .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
              --function-name arn:aws:lambda:eu-west-1:352854872264:function:text2talkFunction \
              --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
        
     
        
 
 